baseURL = "https://wonderful-naiad-8da76d.netlify.app/"
languageCode = "en-us"
title ="Landscapes from over the world"
theme = "PaperMod"

[params]
  author = "Tatiana Barbova"

[pagination]
  pagerSize = 12

[taxonomies]
  location = "locations"
  year = "years"
